from rdkit import Chem
from rdkit.Chem import Draw

# Read the SMILES string from the file generated by molgpt.py
with open("generated_smiles.txt", "r") as f:
    smiles = f.read().strip()

# Convert SMILES to a molecule object
mol = Chem.MolFromSmiles(smiles)

if mol is None:
    print("Invalid SMILES string!")
else:
    # Display the molecule image
    img = Draw.MolToImage(mol)
    img.show()

# # Extract molecular properties using RDKit
# molecular_weight = Descriptors.MolWt(mol)
# logp = Descriptors.MolLogP(mol)
# h_acceptors = Descriptors.NumHAcceptors(mol)
# h_donors = Descriptors.NumHDonors(mol)
# num_rotatable_bonds = Descriptors.NumRotatableBonds(mol)

# # Construct a description of the molecule
# description = f"The molecule with SMILES: {smiles} has the following properties:\n"
# description += f"Molecular weight: {molecular_weight:.2f} g/mol\n"
# description += f"LogP (lipophilicity): {logp:.2f}\n"
# description += f"Number of hydrogen bond acceptors: {h_acceptors}\n"
# description += f"Number of hydrogen bond donors: {h_donors}\n"
# description += f"Number of rotatable bonds: {num_rotatable_bonds}\n"

# # Now use GPT-3/4 to generate an antibiotic-related overview
# openai.api_key = 'your-openai-api-key'

# prompt = (
#     f"Please analyze the following molecule described by its properties and provide a brief overview on "
#     f"how it could potentially be used as an antibiotic.\n\n{description}\n\n"
#     "Also, describe the mechanism of action if possible."
# )

# # Get the model response
# response = openai.Completion.create(
#     engine="text-davinci-003",  # You can use a different engine as well
#     prompt=prompt,
#     max_tokens=150,
#     temperature=0.7
# )

# # Output the response from the model
# print(response.choices[0].text.strip())